###
http://localhost:4004/service/Petition
###
http://localhost:4004/service/Petition
Authorization: Basic bob:
###
https://05e02d6ctrial-dev-petition-api-srv.cfapps.us10-001.hana.ondemand.com/service/Petition
Authorization:  Basic bob:


###
https://05e02d6ctrial.authentication.us10.hana.ondemand.com
Authorization: Basic sb-petition-api-05e02d6ctrial-dev!t123606:2aSszrgUBI7kt58NHuJcGf12sgM=